name: test workflow
on:
  push:
    branches: [main]

jobs:
  Checkout:
    needs: test
    name: checkout the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |-
          cd function
          python -m pip install --upgrade pip 
          if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: create zip
        run: |-
          cd function
          zip -r ../${{ github.sha }}.zip  .
      - name: upload artifcate
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha}}.zip
